#!/usr/bin/env pwsh
# cross-repo-pr.ps1 - Open a PR in another Nostria repo
#
# Usage:
#   pwsh scripts/cross-repo/cross-repo-pr.ps1 -Repo "nostria-app/nostria-website" -Branch "agent/marketing/blog-post" -Title "New blog post" -Body "Generated by marketing agent"

param(
  [Parameter(Mandatory)][string]$Repo,
  [Parameter(Mandatory)][string]$Branch,
  [Parameter(Mandatory)][string]$Title,
  [string]$Body = "Automatically generated by Nostria Operations agent.",
  [string]$BaseBranch = "main",
  [string]$WorkDir = ""
)

$ErrorActionPreference = "Stop"

if (-not $WorkDir) {
  $WorkDir = Join-Path ([System.IO.Path]::GetTempPath()) "nostria-cross-repo-$(Get-Random)"
}

Write-Host "Cloning $Repo to $WorkDir..."
& git clone "https://github.com/$Repo.git" $WorkDir
Push-Location $WorkDir

try {
  Write-Host "Creating branch $Branch..."
  & git checkout -b $Branch

  Write-Host ""
  Write-Host "=========================================="
  Write-Host "Workspace ready at: $WorkDir"
  Write-Host "Branch: $Branch"
  Write-Host ""
  Write-Host "Make your changes, then run:"
  Write-Host "  git add . && git commit -m '$Title' && git push origin $Branch"
  Write-Host "  gh pr create --title '$Title' --body '$Body' --base $BaseBranch --repo $Repo"
  Write-Host "=========================================="
} finally {
  Pop-Location
}
